apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  selector:
      app: backend
  ports:
  - port: {{ .Values.backend.httpPort }}
    targetPort: 3000
  type: ClusterIP