apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql
spec:
  selector:
      app: mysql
  ports:
  - port: {{ .Values.mysql.httpPort }}
    targetPort: 3306
  type: ClusterIP