apiVersion: v1
kind: ConfigMap
metadata:
  name: booking-config
data:
    DB_TYPE: "mysql"
    DB_HOST: "mysql-service"
    DB_PORT: "3306"
    DB_NAME: "travellux"
    LOKI_HOST: "http://loki-grafana-loki-gateway:80/"